### ISSUE TITLE
API is down...please advise...

### ISSUE THREAD

**Issue by ocsports** [fixerAPI/fixer#15] opened 2016-02-08 18:41 UTC

**Comment by hakanensari** [comment] 2016-02-08 19:35
I see no downtime in the past three hours. Perhaps a temporary hiccup on your end?

<img width="349" alt="screen shot 2016-02-08 at 20 33 52" src="https://cloud.githubusercontent.com/assets/31693/12896664/874a17b8-cea3-11e5-8fa0-be3e0b087717.png">

**Comment by ocsports** [comment] 2016-02-11 18:50
So, after some extensive testing I have been able to reproduce the issue fairly consistently.  We have integration tests which synchronously send 8-10 requests in rapid succession.  At some point in this test, we are getting a timeout error (timeout is set to 30 seconds).  This only seems to occur when I fire multiple api requests at your server.  Do you have any constraints on your system on counts per client which would prevent this behavior?  Please see log message below.  Again, there will be one to many successful calls, and then a timeout error...

`bioapi.utility.currency.CurrencyConversionError: "unable to establish connection to url http://api.fixer.io/latest?base=
EUR&symbols=USD - HTTPConnectionPool(host='api.fixer.io', port=80): Max retries exceeded with url: /latest?base=EUR&symb
ols=USD (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7f17645df240>, '
Connection to api.fixer.io timed out. (connect timeout=30)'))"`

**Comment by EdgeCaseBerg** [comment] 2016-02-11 20:41
I just saw this and the https endpoint is working fine, it seems only the http is down.

**Comment by antonioreyna** [comment] 2016-02-12 00:05
is it down? at the moment? thanks.

**Comment by hakanensari** [comment] 2016-02-12 10:34
@ocsports I'm afraid I cannot reproduce. You may want to run the same below to see if it helps identify issue on your end.

``` sh
$ ab -n 1000 -c 50 http://api.fixer.io/latest
This is ApacheBench, Version 2.3 <$Revision: 1528965 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking api.fixer.io (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests


Server Software:        nginx/1.9.9
Server Hostname:        api.fixer.io
Server Port:            80

Document Path:          /latest
Document Length:        452 bytes

Concurrency Level:      50
Time taken for tests:   3.893 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      680000 bytes
HTML transferred:       452000 bytes
Requests per second:    256.86 [#/sec] (mean)
Time per request:       194.657 [ms] (mean)
Time per request:       3.893 [ms] (mean, across all concurrent requests)
Transfer rate:          170.57 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       85   88   2.1     88      93
Processing:    89  102  14.0     98     195
Waiting:       89  102  14.0     98     195
Total:        174  190  14.6    186     288

Percentage of the requests served within a certain time (ms)
  50%    186
  66%    190
  75%    193
  80%    195
  90%    201
  95%    210
  98%    247
  99%    264
 100%    288 (longest request)
```

@EdgeCaseBerg I don't see any issue with the http endpoint. See above.

@antonioreyna Not that I know of.

**Comment by EdgeCaseBerg** [comment] 2016-02-12 14:27
It is working now. Yesterday it wasn't. :confused: 
Do you have any monitoring setup?

-- Also thanks for the service it's very useful!

**Comment by ocsports** [comment] 2016-02-12 17:03
Thank you for all of the comments.  The original issue appears to be on our client side with the python requests library.  We are investigating this issue on our end and will update with any results.

**Comment by hakanensari** [comment] 2016-03-16 18:20
I have a hunch the above stories have to do with the referenced issue. Closing for now.

**Closed as completed by hakanensari** 2016-03-16 18:20 UTC
